name: Check links for a URL

on:
  workflow_dispatch:
    inputs:
      url:
        required: true
      create_issues:
        type: boolean
        description: "Whether to create GitHub issues for broken links"
        default: "false" 
        required: false

permissions:
  contents: read
  issues: write

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Step 2: Set up Node.js Environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Install Required Dependencies
      - name: Install Dependencies
        run: npm install jsdom

      # Step 4: Run the Link Checking Script
      - name: Check Links
        env:
          URL: ${{ inputs.url }}
          BYPASS_SECRET: "none"
        run: node ./src/check-links.js

      # Step 5: Create Issues from Broken Links
      - name: Create Issues for Broken Links
        if: ${{ inputs.create_issues == 'true' }} 
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const data = JSON.parse(fs.readFileSync('./broken-links.json', 'utf8'));

            if (data.length === 0) {
              console.log("🎉 No broken links found!");
              return;
            }

            const issueTitles = new Set(); // To avoid duplicate issues

            for (const brokenLink of data) {
              const { url, status } = brokenLink;
              const title = `Broken Link: ${url}`;

              if (issueTitles.has(title)) continue; // Skip duplicates
              issueTitles.add(title);

              const body = `
              **Broken Link Information**:
              - **URL**: ${url}
              - **Status**: ${status}`;

              // Create a GitHub issue
              const issue = await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title,
                body: body,
                labels: ['broken-link'],
              });

              console.log(`Created issue #${issue.data.number}: ${title}`);
            }
